### ISSUE TITLE
Interoperability with other VC-JWT implementations

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/did-jwt-vc#100]
Cross linking to this work item: https://github.com/decentralized-identity/JWS-Test-Suite/issues/39

We would love to see this repo demonstrate interop for the VC-JWT formats that this code base supports.

**Comment by kimdhamilton** [comment]
starting point addressed with https://github.com/decentralized-identity/JWS-Test-Suite/pull/44. Will open followup issues

**Comment by kimdhamilton** [comment]
@mirceanis -- this issue can be closed

**Comment by mirceanis** [comment]
@kimdhamilton thank you!
