### ISSUE TITLE
[BUG] did-jwt-vc does not appear to handle expirationDate properly

### ISSUE THREAD

**Issue by nick-verida** [decentralized-identity/did-jwt-vc#102]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest version
- [X ] I checked the documentation and found no answer
- [ ]X I checked to make sure that this issue has not already been filed

### Current Behavior

The [verifyCredential](https://github.com/decentralized-identity/did-jwt-vc/blob/135df0867eebac88576e38b1f3290954746faba7/src/index.ts#L196) method does not verify that the `expirationDate` property is not expired. 

### Expected Behavior

From the [spec](https://www.w3.org/TR/vc-data-model/#expiration):

> If present, the value of the expirationDate [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be a string value of an [XMLSCHEMA11-2](https://www.w3.org/TR/xmlschema11-2/#dateTime) ] date-time representing the date and time the [credential](https://www.w3.org/TR/vc-data-model/#dfn-credential) ceases to be valid.

I'd note that it maybe difficult to securely determine the current datetime (eg, if running in a browser this can easily be tampered with) so it maybe necessary to allow users to inject the current date time they get from an external (secure) source. 

I'd also note that the current method makes it _look_ like the Timestamps are being validated (`validateTimestamp`). However, these methods only validate the date format, not validating that they are valid by the W3C rules. It might be worth noting this. 

```
export function validateJwtCredentialPayload(payload: JwtCredentialPayload): void {
  validators.validateContext(payload.vc['@context'])
  validators.validateVcType(payload.vc.type)
  validators.validateCredentialSubject(payload.vc.credentialSubject)
  if (payload.nbf) validators.validateTimestamp(payload.nbf)
  if (payload.exp) validators.validateTimestamp(payload.exp)
}
```

**Comment by mirceanis** [comment]
Hi @nick-verida, can you provide a sample credential that is expired but still verifies as valid?

This library mostly deals with validating that the JWTs follow the Verifiable Credential/Presentation data model.
For the actual verification of signatures and timestamps it relies on `did-jwt`

**Comment by nick-verida** [comment]
> This library mostly deals with validating that the JWTs follow the Verifiable Credential/Presentation data model.
For the actual verification of signatures and timestamps it relies on [did-jwt](https://github.com/decentralized-identity/did-jwt-vc/blob/135df0867eebac88576e38b1f3290954746faba7/src/index.ts#L201)

This is precisely my point.

Despite what that code looks like, it is not actually validating `payload.expirationDate` (!)

The line:

```
if (payload.expirationDate) validators.validateTimestamp(payload.expirationDate)
```

just checks the format of any date, and does not validate against the rules in the spec. It would be better named `checkTimestampFormat` or something. 


To be precise, it does this part: 

> the value of the expirationDate [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be a string value of an [XMLSCHEMA11-2](https://www.w3.org/TR/xmlschema11-2/#dateTime) ] date-time

but ignores this part:

> representing the date and time the [credential](https://www.w3.org/TR/vc-data-model/#dfn-credential) ceases to be valid


> Perhaps we can rename some methods to reduce some confusion.

I would expect any method with `validate` in the name to be validating against specification. There seems to be a missing part here that actually checks these rules.

**Comment by mirceanis** [comment]
I'm OK with deprecating the names of methods I favor of more appropriate names. If you have suggestions for API method renames, please voice them as PRs.

The timestamp comparisons are already performed by did-jwt, so there is no point in repeating them.
