### ISSUE TITLE
[question] Hide information from VCs in VPs

### ISSUE THREAD

**Issue by Aplieox** [decentralized-identity/did-jwt-vc#104]
Hello,

Is there any way to hide informations from VCs in a VP? The Standard describes that such a privacy-enhancing feature should be implemented.
See here: https://www.w3.org/TR/vc-data-model/#presentations

**Comment by Aplieox** [comment]
Thanks for the quick answer. Single purpose Credentials or Credentials witgh minimal private data seem to be the easiest solution.

Happy Coding.

**Comment by bumblefudge** [comment]
@Aplieox , you might want to check out the JsonWebPresentation [work item](https://github.com/json-web-proofs/json-web-proofs) in the Applied Crypto WG at DIF-- it's a greenfield project to add a new form of token to the JSON family for just this purpose.  I'm not sure how committed that WG is to backwards compatibility with presenting today's JWTs selectively (or if that's even mathematically possible!), but it's the best upgrade path I can imagine for today's JWT systems to upgrade to selective disclosure without having to scrap all the JSON tooling!
