### ISSUE TITLE
[BUG] Allow empty credentialSubject

### ISSUE THREAD

**Issue by kimdhamilton** [decentralized-identity/did-jwt-vc#106]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**YOU MAY DELETE THE PREREQUISITES SECTION** if you're sure you checked all the boxes.

### Current Behavior

Validation checking prevents empty `credentialSubject`

### Expected Behavior

JWSTestSuite is expecting empty `credentialSubject` to succeed. It's used as credential-0.json in the input test vectors.

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/jws-2020/v1"
  ],
  "type": ["VerifiableCredential"],
  "issuer": "did:example:123",
  "issuanceDate": "2021-01-01T19:23:24Z",
  "credentialSubject": {}
}
```

Note that this is the reason test vector credential-0 is failing.

### Failure Information

Receive error:

`TypeError: credentialSubject must not be empty`

#### Steps to Reproduce

Clone JWS-Test-Suite and then:
```
cd  JWS-Test-Suite/implementations/did-jwt-vc
npm run install
npm run test
```

#### Failure Logs/Screenshots

```
    TypeError: credentialSubject must not be empty

```

#### Alternatives you considered

Please provide details about an environment where this bug does not occur.

---

> **Don't paste private keys anywhere public!**

**Comment by kimdhamilton** [comment]
@mirceanis -- make me codeowner of this repo. I'll give it love

**Comment by mirceanis** [comment]
> @mirceanis -- make me codeowner of this repo. I'll give it love

You mean create a CODEOWNERS file and link you there? or direct write access?
I can do both, and I'm happy to colaborate on this.

For direct write access, I only ask that you are mindful of semantic versioning.
Versioning and releases are decided automatically [based on commit messages](https://github.com/semantic-release/semantic-release#commit-message-format), which is also the reason we prefer squash-merging PRs.

In the meantime, I'm eager to discover what improvements you would like to make to this repository, in the form of issues :)

**Comment by kimdhamilton** [comment]
@mirceanis, no need to create a CODEOWNERS file -- I just want to help handle PRs, issues, etc. Ack on semantic versioning. I'll make sure I'm subscribed to did-jwt as well

**Comment by mirceanis** [comment]
> @mirceanis, no need to create a CODEOWNERS file -- I just want to help handle PRs, issues, etc. Ack on semantic versioning. I'll make sure I'm subscribed to did-jwt as well

Wonderful!

I added you as maintainer here and on did-jwt.

**Comment by mirceanis** [comment]
It seems that the behavior is correct (see #107) so I'm closing this

**Comment by kimdhamilton** [comment]
Thanks @mirceanis -- completely agree on closing this
