### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ajunge** [decentralized-identity/did-jwt-vc#11]
Document all the missing methods

**Comment by OR13** [comment]
including verification :)

**Comment by OR13** [comment]
https://github.com/decentralized-identity/did-jwt-vc/blob/develop/src/index.ts

**Comment by ajunge** [comment]
@mi-xu @mirceanis  is this solved with PR #12 ?

**Comment by mirceanis** [comment]
yes.
closing it.
