### ISSUE TITLE
New JWT-VC 2.0 spec support

### ISSUE THREAD

**Issue by astanciu** [decentralized-identity/did-jwt-vc#127]
Any plans to add support for the new native jwt-vc 2.0 spec? https://w3c.github.io/vc-jwt/#version-2

A little context here:
https://self-issued.info/?p=2316

**Comment by OR13** [comment]
I might suggest holding off support until the document gets to FPWD.

**Comment by mirceanis** [comment]
yup, for jwt-vc 2.0 we might not even need this library. :)
