### ISSUE TITLE
[BUG] IssuerType wrongly defined

### ISSUE THREAD

**Issue by pasquale95** [decentralized-identity/did-jwt-vc#128]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**YOU MAY DELETE THE PREREQUISITES SECTION** if you're sure you checked all the boxes.

### Current Behavior

The type definition of the `issuer` field inside `NarrowCredentialDefinition` is not correctly interpreted by TS.
The current type definition of the issuer field in `NarrowCredentialDefinition` is:
```js
interface NarrowCredentialDefinitions {
    '@context': string[];
    type: string[];
    issuer: Exclude<IssuerType, string>;
    issuanceDate: string;
    expirationDate?: string;
}
```
If I try to assign a string to the issuer field I get an error by the typescript interpreter:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/26608445/220963406-95fe26ea-91fd-4c1d-a54f-33f770b50dfb.png">

### Expected Behavior

On the contrary, I should be able to assign a string to the `issuer` field, as specified in the [documentation](https://www.w3.org/TR/vc-data-model/#issuer).
The fix is as simple as defining the `NarrowCredentialDefinition` as follows in [types.ts](https://github.com/decentralized-identity/did-jwt-vc/blob/master/src/types.ts#L98):
```js
interface NarrowCredentialDefinitions {
    '@context': string[];
    type: string[];
    issuer: IssuerType;
    issuanceDate: string;
    expirationDate?: string;
}
```

### Failure Information

The issue is present on JetBrains and Visual Studio Code.

### Additional information

Let me know if you manage to fix this by yourself or if I have to create a PR.

**Comment by mirceanis** [comment]
The `W3CCredential` type in this library is meant to represent an unambiguous representation of the properties of a Verifiable Credential.

The spec is very flexible in what credentials can contain and how their properties are laid out, but this means that it is very difficult to deal with credentials programmatically without dealing with a lot of corner cases.

The `W3CCredential` data type is meant to help relieve some of that difficulty by fixing some of the properties to a more easily parsable state. It is usually the result of a parsing operation and not meant to be used as a basis for creating credentials.

If you're building credential payloads, please use the `CredentialPayload` data type.

**Comment by pasquale95** [comment]
What's the advantage of declaring the issuer as `Exclude<IssuerType, string>`? The result is an incorrect type for the `issuer` field, which can be a simple string.

**Comment by mirceanis** [comment]
If you avoid the string, then you can always get the issuer from `issuer.id` instead of needing to check the datatype type first.
