### ISSUE TITLE
[BUG] Conflict between VC Data Model specification and `JwtCredentialPayload`

### ISSUE THREAD

**Issue by ankurdotb** [decentralized-identity/did-jwt-vc#136]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Current Behavior

The payload section of a JWT VC [as defined in `JwtCredentialPayload`](https://github.com/decentralized-identity/did-jwt-vc/blob/64769d634003d3f89edd68aaf5ad9c343b43793b/src/types.ts#L30) only retains the following fields after normalisation:

```jsonc
export interface JwtCredentialPayload {
  iss?: string
  sub?: string
  vc: Extensible<{
    '@context': string[] | string
    type: string[] | string
    credentialSubject: JwtCredentialSubject
    credentialStatus?: CredentialStatus
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    evidence?: any
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    termsOfUse?: any
  }>
  nbf?: number
  aud?: string | string[]
  exp?: number
  jti?: string

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [x: string]: any
}
```

This will skip values such as `issuer`, `issuanceDate`, `expirationDate` etc - anything not explicitly mentioned above.

### Expected Behavior

According to the [VC Data Model specification, Section 4.5 Issuer](https://www.w3.org/TR/vc-data-model/#issuer), these fields **should** be in the `vc` field and **duplicated** to native JWT fields such as `iss`, `nbf`, etc. Jump to [Example 8 and switch to the "Verifiable Credential (as JWT)" tab](https://www.w3.org/TR/vc-data-model/#example-usage-of-issuer-property):

> --------------- JWT payload ---------------
// NOTE: The example below uses a valid VC-JWT serialization
//       that duplicates the iss, nbf, jti, and sub fields in the
//       Verifiable Credential (vc) field.

If you look at the JWT in that example:

```
eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3
d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L
2NyZWRlbnRpYWxzL2V4YW1wbGVzL3YxIl0sImlkIjoiaHR0cDovL2V4YW1wbGUuZWR1L2NyZWRl
bnRpYWxzLzM3MzIiLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiVW5pdmVyc2l0eUR
lZ3JlZUNyZWRlbnRpYWwiXSwiaXNzdWVyIjoiaHR0cHM6Ly9leGFtcGxlLmVkdS9pc3N1ZXJzLz
E0IiwiaXNzdWFuY2VEYXRlIjoiMjAxMC0wMS0wMVQxOToyMzoyNFoiLCJjcmVkZW50aWFsU3Via
mVjdCI6eyJpZCI6ImRpZDpleGFtcGxlOmViZmViMWY3MTJlYmM2ZjFjMjc2ZTEyZWMyMSIsImRl
Z3JlZSI6eyJ0eXBlIjoiQmFjaGVsb3JEZWdyZWUiLCJuYW1lIjoiQmFjaGVsb3Igb2YgU2NpZW5
jZSBhbmQgQXJ0cyJ9fX0sImlzcyI6Imh0dHBzOi8vZXhhbXBsZS5lZHUvaXNzdWVycy8xNCIsIm
5iZiI6MTI2MjM3MzgwNCwianRpIjoiaHR0cDovL2V4YW1wbGUuZWR1L2NyZWRlbnRpYWxzLzM3M
zIiLCJzdWIiOiJkaWQ6ZXhhbXBsZTplYmZlYjFmNzEyZWJjNmYxYzI3NmUxMmVjMjEifQ.oOoii
TBKC6zbJ8rx916SSHEKk4Fhc5-gFD8Qh64zRsf5ea7D-bu9zA1ii12hnXLloL7Cz0reXKA9P1nB
ZzQvTw
```

...the payload decodes to:

```json
{
  "vc": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://www.w3.org/2018/credentials/examples/v1"
    ],
    "id": "http://example.edu/credentials/3732",
    "type": [
      "VerifiableCredential",
      "UniversityDegreeCredential"
    ],
    "issuer": "https://example.edu/issuers/14",
    "issuanceDate": "2010-01-01T19:23:24Z",
    "credentialSubject": {
      "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
      "degree": {
        "type": "BachelorDegree",
        "name": "Bachelor of Science and Arts"
      }
    }
  },
  "iss": "https://example.edu/issuers/14",
  "nbf": 1262373804,
  "jti": "http://example.edu/credentials/3732",
  "sub": "did:example:ebfeb1f712ebc6f1c276e12ec21"
}
```

You'll see the `iss` value is **copied** in, and `issuer` is left intact under `vc` field.

The [VC-JWT specification](https://w3c.github.io/vc-jwt/), which is a **separate** specification, _also_ uses a very similar example where those fields are left intact under `vc` ([Example 6 in the specification](https://w3c.github.io/vc-jwt/#example-verifiable-credential-encoded-as-jwt)):

```
eyJraWQiOiJ1cm46ZXhhbXBsZTppc3N1ZXIja2V5LTAiLCJhbGciOiJFUzI1NiIsInR5cCI6InZjK2xkK2p3dCIsImN0eSI6InZjK2xkK2pzb24ifQ.eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvbnMvY3JlZGVudGlhbHMvdjIiXSwiaWQiOiJodHRwOi8vZXhhbXBsZS5lZHUvY3JlZGVudGlhbHMvMzczMiIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJVbml2ZXJzaXR5RGVncmVlQ3JlZGVudGlhbCJdLCJpc3N1ZXIiOiJodHRwczovL2V4YW1wbGUuZWR1L2lzc3VlcnMvMTQiLCJpc3N1YW5jZURhdGUiOiIyMDEwLTAxLTAxVDE5OjIzOjI0WiIsImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImlkIjoiZGlkOmV4YW1wbGU6MTIzIiwiZGVncmVlIjp7InR5cGUiOiJCYWNoZWxvckRlZ3JlZSIsIm5hbWUiOiJCYWNoZWxvciBvZiBTY2llbmNlIGFuZCBBcnRzIn19fQ.pfbhgWlTUZA8WmoFbi8WEIUFyC_lSQaAswoW87D1YeimdWZLq4MiJ3o-CmTkvkEQFhffvRiCzmkhxjS_R_RdOw
```

Which decodes to:

```json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "id": "http://example.edu/credentials/3732",
  "type": [
    "VerifiableCredential",
    "UniversityDegreeCredential"
  ],
  "issuer": "https://example.edu/issuers/14",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:123",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  }
}
```

### Failure Information

N/A

#### Steps to Reproduce

As above. This is more of a standards vs implementation point, for anything that does create credential.

#### Environment Details

N/A - affects all situations and is not environment dependent.

### Discussion

1. Both the VC Data Model and VC JWT specifications say fields like `iss`, `nbf` etc should be **duplicated**, but this implementation deviates from that. Which one is correct?
2. If there's agreement, we're happy to create a PR to fix this, but IMO we need agreement first on whether the specification is wrong or the implementation.
3. Prior discussions: https://github.com/decentralized-identity/did-jwt-vc/issues/73, https://github.com/decentralized-identity/did-jwt-vc/issues/102

**Comment by ankurdotb** [comment]
I think I partially narrowed down where the confusion arises from:

- https://www.w3.org/TR/vc-data-model/#issuer <- this is the issuer section in **VC Data Model v1.1**, the t**echnical recommendation**. This is where the VC Data Model example above is from.
- https://w3c.github.io/vc-data-model/#issuer <- This is **VC Data Model 2.0**, the **working draft**. The issuer section is _different_ here.

However, the conflict between VC JWT specification and the implementation still exists as evidenced by the second example.

**Comment by mirceanis** [comment]
It's also worth noting that the JWT example in https://www.w3.org/TR/vc-data-model/#issuer contradicts the JWT spec which requires the iss property to be a string

**Comment by mirceanis** [comment]
We added the `removeOriginalFields` option to methods dealing with creating tokens to allow you to duplicate the data.
It defaults to true, but you can set it to false to duplicate

**Comment by ankurdotb** [comment]
@nklomp Sounds like it the current implementation of `removeOriginalFields` is perhaps then the issue (as in example above)?

**Comment by ankurdotb** [comment]
Is the use case of being just passed the payload section of JWT common? Your logic might work if JWT payloads _always_ nest the values under `vc` but I'm not sure whether that's logic everyone expects.

Wouldn't a better way be to _always_ normalise top-level/final output like so regardless of whether `removeOriginalFields` is true or false):

- `vc` or `vp` (if `true`, remove `issuer` etc) <- Don't care whether original payload was JWT or not
- `JWT specific fields (`iss`, `nbf`, etc)
- Remove anything else at the top level

BTW, a tangible example of where the VCDM fields as well as their replication in `vc` is left behind is the when doing `veramo credential create`.

**Comment by ankurdotb** [comment]
(On a related note, I raised this issue on the VC JWT specification https://github.com/w3c/vc-jwt/issues/100 separately because it relates to the header in VC JWTs, and I didn't want to keep that separate.)

**Comment by ankurdotb** [comment]
@OR13 Do you have any thoughts on this one? Would appreciate your advice.

**Comment by OR13** [comment]
I don't think v1 was implementable for JWT, at least in a way that was interoperable.

v2 essentially says , don't delete any required fields, don't use `vc` or `vp` and you can add any registered claims you like to the claimset.

I'd start heading that direction, but it's possible the target will have moved by the time you get there.
