### ISSUE TITLE
Module '"../node_modules/did-jwt-vc/lib"' has no exported member 'Issuer'

### ISSUE THREAD

**Issue by kst-howest** [decentralized-identity/did-jwt-vc#15]
Hi,

I installed did-jwt-vc using npm install did-jwt-vc.

Next compiling  index.ts file fails with the error message _Module '"../node_modules/did-jwt-vc/lib"' has no exported member 'Issuer'_

import EthrDID from 'ethr-did'
import { Issuer } from 'did-jwt-vc'
const ethrDid = new EthrDID({address: '0xf1232f840f3ad7d23fcdaa84d6c66dac24efb198', privateKey: 'd8b595680851765f38ea5405129244ba3cbad84467d190859f4c8b20c1ff6c75', provider})

Can someone help? Thanks

**Comment by aldigjo** [comment]
Hi Please try importing like this `import { Issuer } from 'did-jwt-vc/lib/types'`

**Comment by kst-howest** [comment]
Hi, this solved the issue. Thank you!

Next, if I write instead in my index.ts file:
const issuer: Issuer = new EthrDID({
    address: '0xf1232f840f3ad7d23fcdaa84d6c66dac24efb198',
    privateKey: 'd8b595680851765f38ea5405129244ba3cbad84467d190859f4c8b20c1ff6c75'
  })

This gets compiled with tsc into index.js file
"use strict";
exports.__esModule = true;
var ethr_did_1 = require("ethr-did");
var issuer = new ethr_did_1["default"]({
    address: '0xf1232f840f3ad7d23fcdaa84d6c66dac24efb198',
    privateKey: 'd8b595680851765f38ea5405129244ba3cbad84467d190859f4c8b20c1ff6c75'
});

which results in following error with node index.js 

var issuer = new ethr_did_1["default"]({
             ^
TypeError: ethr_did_1.default is not a constructor
    at Object.<anonymous> (/home/kst/sem3/src/index.js:7:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3


PS. Sorry newbie questions to javascript & typescript

**Comment by aldigjo** [comment]
Hmm seems to be some sort of quirk with typescript, try doing it like this 

`import * as EthrDID from 'ethr-did'`

**Comment by kst-howest** [comment]
Hi, thanks again, that solved it as well :-)

**Comment by kst-howest** [comment]
Hi, trying the other code from the Readme.md file, a few other modifications are needed it seems:

import { Issuer } from 'did-jwt-vc/lib/types'
import * as EthrDID from 'ethr-did'
import { VerifiableCredentialPayload } from 'did-jwt-vc/lib/types'
import {  createVerifiableCredential } from 'did-jwt-vc'
import { createPresentation } from 'did-jwt-vc'
import { PresentationPayload } from 'did-jwt-vc/lib/types'
import { getResolver } from 'ethr-did-resolver'
import { verifyCredential } from 'did-jwt-vc'

Remaining problem is now:
import { Resolver } from 'did-resolver'
const resolver = new Resolver(getResolver())

The interpreter doesn't find the Resolver in did-resolver. 
Tried a few alternatives import * as Resolver from 'did-resolver' and import { Resolver } from 'did-resolver/lib/resolve' however without any luck.

best regards

**Comment by mirceanis** [comment]
@kst-howest what interpreter are you using?
As far as I know, the examples are in typescript.

Can you provide an example project where these errors occur?

**Comment by kst-howest** [comment]
Hi, i'ḿ using visual studio code with tsc on ubuntu
Attaching a test.zip file with 2 files
-  index.ts file (under src/) 
-  tsconfig.json.

The index.ts file is simply a copy & paste of the readme.md code snippets, with a hello message just for debugging purposes.

br
[test.zip](https://github.com/decentralized-identity/did-jwt-vc/files/4041678/test.zip)
