### ISSUE TITLE
Resolve not found in did-resolver package

### ISSUE THREAD

**Issue by kst-howest** [decentralized-identity/did-jwt-vc#16]
[test.zip](https://github.com/decentralized-identity/did-jwt-vc/files/4061227/test.zip)
Hi, trying the other code from the Readme.md file, a few other modifications are needed it seems:

import { Issuer } from 'did-jwt-vc/lib/types'
import * as EthrDID from 'ethr-did'
import { VerifiableCredentialPayload } from 'did-jwt-vc/lib/types'
import { createVerifiableCredential } from 'did-jwt-vc'
import { createPresentation } from 'did-jwt-vc'
import { PresentationPayload } from 'did-jwt-vc/lib/types'
import { getResolver } from 'ethr-did-resolver'
import { verifyCredential } from 'did-jwt-vc'

Remaining problem is now:
import { Resolver } from 'did-resolver'
const resolver = new Resolver(getResolver())

TSC doesn't find the Resolver in did-resolver.
Tried a few alternatives import * as Resolver from 'did-resolver' and import { Resolver } from 'did-resolver/lib/resolve' however without any luck.
br, Kris
[test.zip](https://github.com/decentralized-identity/did-jwt-vc/files/4061230/test.zip)

**Comment by mirceanis** [comment]
that's weird, `did-resolver` is also a TS lib and exports that type directly.
which version are you using?

**Comment by kst-howest** [comment]
tsc -version > Version 3.7.4

**Comment by mirceanis** [comment]
I mean which version of `did-resolver` are you using?
It's easier if you keep track of things with a `package.json` file.

Also, perhaps it's wise to take care of those `await` errors too.
A quick fix for those is wrapping your code in an `async` anonymous function like so:

```typescript
(async () => {
  //...your code here
})();
```

**Comment by kst-howest** [comment]
Hi, I ran again "npm install did-resolve" and seemed to have updated to
did-resolver@1.1.0
and now it seems working :-)
Thanks for your help and for the async/await advice!

**Comment by mirceanis** [comment]
excellent
