### ISSUE TITLE
About verifyCredential & verifyPresentation parameters.

### ISSUE THREAD

**Issue by kryptojet** [decentralized-identity/did-jwt-vc#22]
A verifyJWT function can use options not only resolver  but also audience, auth, and callbackUrl.
Why use only vc(or presentation) and  resolver as paramters in a function?

```
export async function verifyCredential(vc: string, resolver: Resolvable): Promise<any> {
  const verified = await verifyJWT(vc, { resolver })
  if(isLegacyAttestationFormat(verified.payload)) {
    verified.payload = attestationToVcFormat(verified.payload)
  }
  validateVerifiableCredentialAttributes(verified.payload)
  return verified
}

export async function verifyPresentation(presentation: string, resolver: Resolvable): Promise<any> {
  const verified = await verifyJWT(presentation, { resolver })
  validatePresentationAttributes(verified.payload)
  return verified
}
```

**Comment by mirceanis** [comment]
That's a good suggestion.
Can you give some more details about how the API you envision would look like?

**Comment by kryptojet** [comment]
According to the vc-data-model document, use `audience` to use `aud` for backward compatibility with JWT processors. And there is an example of using `aud` in the example, but `aud` cannot be used for proof because `audience` is blocked. So, I suggest that all paramters be used for compatibility.

**Comment by mirceanis** [comment]
It looks like options are not forwarded to `did-jwt` during verification so this issue is still open
