### ISSUE TITLE
transformPresentationInput mutates the input object

### ISSUE THREAD

**Issue by simonas-notcat** [decentralized-identity/did-jwt-vc#40]
I've created this failing test to show where the problem is.
https://github.com/decentralized-identity/did-jwt-vc/commit/99b09bd0c9dde2e00d4998cff59f5ffeff684999

@mirceanis I eventually got around this problem, by not calling this method directly https://github.com/uport-project/daf/commit/df40d7e12750b7016c693f1a3f86c83bda4a0e89#diff-d76fa3686d6633d10d70955ec9a764daL98

**Comment by mirceanis** [comment]
nice catch.
