### ISSUE TITLE
Java Support (proposal)

### ISSUE THREAD

**Issue by youngjoon-lee** [decentralized-identity/did-jwt-vc#51]
Hi DIF, 

I've implemented the Java version of this `did-jwt-vc` SDK. 
https://github.com/medibloc/vc-java

That implementation is WIP, but was designed as general as possible, so that that can be used with any kinds of DIDs or other key pairs.
Also, I've tried to make it compatible with this `did-jwt-vc`.

So, I think it would be great if my implementation is managed under the [decentralized-identity](https://github.com/decentralized-identity) Github organization, if you don't have any plan to release the Java SDK.

If it's okay, I can refine my implementation and post the official proposal to you.

Thank you.

**Comment by nembal** [comment]
Hi Youngjoon,

Thanks for the implementation. A quick question before we can discuss the proposal. 
Are you employed by a DIF member org, or are you a freelancer? 
Could you shoot me an email at membership@identity.foundation to discuss IPR? 

I will ping the WG chairs about the technical aspect of the question.

**Comment by youngjoon-lee** [comment]
@nembal Thank you for your quick reply. I just sent you an email :)
