### ISSUE TITLE
Verifiable Presentation Clarification

### ISSUE THREAD

**Issue by wip-abramson** [decentralized-identity/did-jwt-vc#58]
I am confused by the verifiable presentation API and process.

The README [here](https://github.com/decentralized-identity/did-jwt-vc#creating-a-verifiable-presentation) states you create a VP by passing in the **issuer** DID, which is used to create a signed JWT.

This seems wrong to me. The issuer uses their EthrDID to sign the VC, they then give that to the holder. The holder does not or at least should not, have to know the issuers keys to create a VP. They may want to use the keys associated with the subject of the credential to sign the VP. Is this just a mistake in the README?

Should it be
```javascript
    let vpPayload = {
        vp: {
            '@context': ['https://www.w3.org/2018/credentials/v1'],
            type: ['VerifiablePresentation'],
            verifiableCredential: [vcJWT]
        }
    }

    vpJWT = await didJWT.createVerifiablePresentationJwt(vpPayload, subject)
```

Also, this library includes no API for liveness through a challenge-sign-response type flow that would protect against replay's. In effect signing a VP seems pretty pointless without this. I could have got this signed presentation object from my friend last week, or by listening on the wire last year.

Quite possibly I am missing something here, but by going through the README and setting up a basic example that is my interpretation. Is this just out of scope and left to an implementor to handle protection against replay?

Thanks

**Comment by OR13** [comment]
Yes, typically a verifiable presentation is made in response to a `domain` and `challenge`... see https://w3c-ccg.github.io/vc-http-api/#operation/provePresentation

**Comment by OR13** [comment]
However, its also legal to have a VP that has no proof... https://github.com/w3c-ccg/vc-http-api/pull/95#issuecomment-777603045

And its useful...

**Comment by wip-abramson** [comment]
Right, thanks Orie. And that is a yes this is out of scope in this jwt library?

Could you explain what creating a Verifiable Presentation Jwt does then. It creates a signed presentation right? Am I write in saying this should be signed by the subject. What is the point of this without a challenge?

It is quite a different approach contrasted to this https://github.com/digitalbazaar/vc-js

**Comment by OR13** [comment]
We have our own version of that library with some changes we made to support React Native (thanks contributions from DIF members)...

https://github.com/transmute-industries/vc.js

We support vc-jwt, but none of our customers use it, and we are required to produce Linked Data Proof based VCs by all of our customers.

**Comment by mirceanis** [comment]
Thanks for pointing this out, @wip-abramson!

The naming of some parameters and the way they are documented can be improved.
The documentation you pointed to should refer to the holder, not the issuer, and this is a bug in the docs.

From the perspective of JWT encoded credentials and presentations, both issuer and holder get translated to `iss` in the JWT payload, and it's very likely that this is the origin of this confusion.

This library does not enforce the use of the `domain` and `challenge` parameters that can (and in many cases should) be added to a presentation. They can, however, be added to the JWT payload when you are creating the presentation.
I'm not aware of the use of these parameters with JWT verifiable presentations, or if this has been specified.

If you have suggestions about how this library and the docs can be improved, please keep sharing

**Comment by awoie** [comment]
I'd say...

- `nonce` <-> `challenge`
- `aud`<-> `domain`

**Comment by wip-abramson** [comment]
Ah okay so to implement this I would create a vp like:

```javascript
    let vpPayload = {
        vp: {
            '@context': ['https://www.w3.org/2018/credentials/v1'],
            type: ['VerifiablePresentation'],
            verifiableCredential: [vcJWT]
        }
        nonce: "123454"
        aud: "www.example.com"
    }
```

And then sign it.

**Comment by mirceanis** [comment]
Exactly.
Although, there is a bug (#22) that prevents the proper verification of this using this library.
Until that is fixed, you can use [`did-jwt`](https://github.com/decentralized-identity/did-jwt) directly to verify the signature and `aud`, and then extract the `nonce` from the returned payload to match against the expected value.

**Comment by rado0x54** [comment]
I've created a PR for the issuer->holder rename and create a separate issue (#60) around the challenge/domain part. I'd therefore propose to close this issue, after the merge.

**Comment by mirceanis** [comment]
Closing this as #59 is merged.
Please reopen if extra clarity is needed that is not covered by #60
