### ISSUE TITLE
Support domain/challenge in VP creation and verification.

### ISSUE THREAD

**Issue by rado0x54** [decentralized-identity/did-jwt-vc#60]
LD-Proof Presentations specify a [challenge](https://w3c-ccg.github.io/ld-proofs/#dfn-challenge) and [domain](https://w3c-ccg.github.io/ld-proofs/#dfn-domain) field in order to support replay protection directly within a Verifiable Presentation.

We would like to support the same functionality natively in the VC/VP [JSON Web Token Specification](https://www.w3.org/TR/vc-data-model/#json-web-token) and therefore propose the following mapping:

LD Proof Representation <-> VP JWT Representation
`challenge` <-> `nonce` (taken from [OpenID token representation](https://openid.net/specs/openid-connect-core-1_0.html#IDToken))
`domain` <-> `aud`

For this ticket the following implementations need to be updated:
```
function verifyPresentation(
  presentation: JWT, resolver: Resolvable): Promise<VerifiedPresentation>
```
to take an optional challenge and domain parameter that gets signed into the VP as part of an external request process.
```
export async function createVerifiablePresentationJwt(
  payload: JwtPresentationPayload | PresentationPayload,
  holder: Issuer
): Promise<JWT>
```
to take an optional challenge and domain parameter that gets verified against the Payload. If no challenge / domain are passed, no additional verifications are performed.

Note, this ticket / library is not responsible for implementing a VC/VP request process that contains the challenge / domain that the VP needs to include in the response.

**Comment by rado0x54** [comment]
At Oliver, is it a problem that `aud` is already specified in the [VP Spec](https://www.w3.org/TR/vc-data-model/#json-web-token) as
```
aud MUST represent (i.e., identify) the intended audience of the verifiable presentation (i.e., the verifier intended by the presenting holder to receive and verify the verifiable presentation).
```
Does that support the intended usage?

**Comment by mirceanis** [comment]
This relates to #22

**Comment by awoie** [comment]
> @awoie, is it a problem that `aud` is already specified in the [VP Spec](https://www.w3.org/TR/vc-data-model/#json-web-token) as
> 
> ```
> aud MUST represent (i.e., identify) the intended audience of the verifiable presentation (i.e., the verifier intended by the presenting holder to receive and verify the verifiable presentation).
> ```
> 
> Does that support the intended usage?

yes, `aud` (JWT) and `domain` (LD-Proofs) are similar in its purpose.
