### ISSUE TITLE
Clarify payload transformation behavior

### ISSUE THREAD

**Issue by mirceanis** [decentralized-identity/did-jwt-vc#62]
The [W3C VC data model](https://www.w3.org/TR/vc-data-model/#jwt-encoding) defines some rules that need to be applied when encoding and decoding Verifiable Credentials and Presentations to and from the JWT payload format.

These rules do not cover several edge cases, like what if the payload contains both entries before a transformation is attempted, what if these entries convert to different values, or what to do with the original fields (delete them or not?).

This library provides the methods:
*  `transformCredentialInput(credential)` - encode to JWT payload format
*  `transformPresentationInput(presentation)` - encode to JWT payload format
*  `normalizeCredential(JWT)` - decode from JWT payload format
* ` normalizePresentation(JWT)` - decode from JWT payload format

The default behavior of these methods is to delete the transformed entries from the output during conversion.
This is behavior differs from other implementations, such as the one from `vc.js` which prefers to duplicate the entries.
Also, there are some examples of JWT credentials that circulate in the community that also display this duplication.
While this duplication is inefficient and unfortunate, it leads to incompatibilities when trying to use this library to generate similar examples.
(see https://github.com/uport-project/veramo/issues/394)

To accommodate these differences the default behavior should be adjusted here as well to keep the originals when performing encode/decode.
This would be a breaking change, but if required, the existing behavior could be reenabled with a flag passed to the encoding methods.

**Comment by rado0x54** [comment]
Hey @mirceanis, can you point me to an example for 

> This is behavior differs from other implementations, such as the one from vc.js which prefers to duplicate the entries.

because I felt this property conversion was unique to the JWT conversion we are doing in this library. Where does vc.js need to convert/duplicate properties of an input VC?

**Comment by mirceanis** [comment]
Sure, here is some JWT issuance code from [transmute-industries/vc.js](https://github.com/transmute-industries/vc.js/blob/43440d7465fe6126460e89be3db6267c90c3bac5/packages/vc.js/src/vc-jwt/issue.ts#L17)
The relevant properties of the `credentialTemplate` are used to generate the corresponding properties of the JWT `payload` but are not removed from the original template.

Also, the JWT examples in the [well known did config spec](https://identity.foundation/.well-known/resources/did-configuration/#example-6-jwt-payload) follow the same pattern.
This means that this library can't be used to generate similar JWTs for domain linkage credentials because it is removing the entries during the transformation.

**Comment by rado0x54** [comment]
Thanks! I'll reach out to Orie I think the community would generally settle on a duplication. Then the optional parameter could be removed again. But until then we can keep it in there.

**Comment by mirceanis** [comment]
IMO duplication is not only inefficient but also opens up a lot of edge cases.
What do you do if the values of the duplicate properties are different?
I would go the opposite way and define an unambiguous transformation.
