### ISSUE TITLE
[BUG] Not possible to set expiresIn or canonicalize when creating a VC

### ISSUE THREAD

**Issue by nikolockenvitz** [decentralized-identity/did-jwt-vc#89]
Hello,
I was not able to create a VC with an expiry time. I see no way of setting the option `expiresIn` of the underlying library `did-jwt` because I cannot inject further options in the second argument.

```javascript
// did-jwt
export async function createJWT(
  payload: Partial<JWTPayload>,
  { issuer, signer, alg, expiresIn, canonicalize }: JWTOptions,
  header: Partial<JWTHeader> = {}
): Promise<string> { // ...
```
https://github.com/decentralized-identity/did-jwt-vc/blob/170ab4032720ac1358b5e0274c92a29cfd97c219/src/index.ts#L75-L85

Similarly, `canonicalize` in the JWTOptions (`did-jwt`) cannot be set.

**Comment by mirceanis** [comment]
Good catch!
Are you willing to contribute a PR with a fix?

**Comment by nikolockenvitz** [comment]
I noticed that expiration time can also be defined by setting `exp` directly in the payload. However, for `canonicalize` such workarounds are not possible and using `expiresIn` might also be more comfortable to use in some cases.
